### ISSUE TITLE
示例库中css片段问题

### ISSUE THREAD

**Issue by EternalZeus** [ProudBenzene/Reverse1999Wiki-in-Obsidian#6]
<img width="577" alt="image" src="https://github.com/user-attachments/assets/24871df5-909c-4ecf-9928-e9fbe7f7476d" />
佬，关于你使用的文件夹添加头像.css,我好像无法修改默认的头像，改了url还是一样

**Comment by ProudBenzene** [comment]
可以把图片链接发在这里吗？我看一下

**Comment by EternalZeus** [comment]
我自己解决了，打扰了

**Comment by ProudBenzene** [comment]
好的👍
